# ============================================================
# POSTGRESQL - NEON
# ============================================================
#db.url=jdbc:postgresql://ep-restless-hall-aehwldwn-pooler.c-2.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.url=jdbc:postgresql://ep-royal-cherry-b4nu0ilv-pooler.c-6.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.username=neondb_owner
db.password=npg_eCKtBImTfp76
# ========================================================lleer contraseña desde varialble de enteorno ====
# DDL
# ===========================================================se conecta a otra base de datos =
db.ddl.auto=false
db.ddl.script=schema_sv.sql