-- SysVentas - esquema H2 (idempotente: se puede ejecutar en cada arranque)

CREATE TABLE IF NOT EXISTS emisor (
                                      id_emisor        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      ruc              VARCHAR(20) NOT NULL,
    nombre_comercial VARCHAR(60) NOT NULL,
    ubigeo           VARCHAR(10) NOT NULL,
    domicilio_fiscal VARCHAR(60) NOT NULL,
    urbanizacion     VARCHAR(40) NOT NULL,
    departamento     VARCHAR(30) NOT NULL,
    provincia        VARCHAR(30) NOT NULL,
    distrito         VARCHAR(30) NOT NULL
    );

CREATE TABLE IF NOT EXISTS perfil (
                                      id_perfil INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      nombre    VARCHAR(20) NOT NULL,
    codigo    VARCHAR(60) NOT NULL
    );

CREATE TABLE IF NOT EXISTS proveedor (
                                         id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         dniruc       VARCHAR(12) NOT NULL,
    nombres_raso VARCHAR(60) NOT NULL,
    tipo_doc     VARCHAR(12) NOT NULL,
    celular      VARCHAR(12) NOT NULL,
    email        VARCHAR(40) NOT NULL,
    direccion    VARCHAR(80) NOT NULL
    );

CREATE TABLE IF NOT EXISTS unid_medida (
                                           id_unidad     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           nombre_medida VARCHAR(40) NOT NULL
    );

CREATE TABLE IF NOT EXISTS usuario (
                                       id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       usuario    VARCHAR(20) NOT NULL,
    clave      VARCHAR(60) NOT NULL,
    estado     VARCHAR(10) NOT NULL,
    id_perfil  INTEGER NOT NULL REFERENCES perfil (id_perfil)
    );

CREATE TABLE IF NOT EXISTS comp_carrito (
                                            id_compcarrito  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            id_proveedor    INTEGER NOT NULL,
                                            id_producto     INTEGER NOT NULL,
                                            nombre_producto VARCHAR(40) NOT NULL,
    cantidad        DOUBLE PRECISION NOT NULL,
    punitario       DOUBLE PRECISION NOT NULL,
    ptotal          DOUBLE PRECISION NOT NULL,
    estado          INTEGER NOT NULL,
    id_usuario      INTEGER NOT NULL REFERENCES usuario (id_usuario)
    );

CREATE TABLE IF NOT EXISTS vent_carrito (
                                            id_carrito      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            dniruc          VARCHAR(12) NOT NULL,
    id_producto     INTEGER NOT NULL,
    nombre_producto VARCHAR(40) NOT NULL,
    cantidad        DOUBLE PRECISION NOT NULL,
    punitario       DOUBLE PRECISION NOT NULL,
    ptotal          DOUBLE PRECISION NOT NULL,
    estado          INTEGER NOT NULL,
    id_usuario      INTEGER NOT NULL REFERENCES usuario (id_usuario),
    tipo_producto   VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS compra (
                                      id_compra    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      precio_base  DOUBLE PRECISION NOT NULL,
                                      igv          DOUBLE PRECISION NOT NULL,
                                      precio_total DOUBLE PRECISION NOT NULL,
                                      serie        VARCHAR(10) NOT NULL,
    num_doc      VARCHAR(12) NOT NULL,
    tipo_doc     VARCHAR(20) NOT NULL,
    fecha_comp   DATE NOT NULL,
    fecha_reg    DATE NOT NULL,
    id_proveedor INTEGER NOT NULL REFERENCES proveedor (id_proveedor),
    id_usuario   INTEGER NOT NULL REFERENCES usuario (id_usuario)
    );

CREATE TABLE IF NOT EXISTS cliente (
                                       dniruc         VARCHAR(12) PRIMARY KEY,
    nombres        VARCHAR(60) NOT NULL,
    rep_legal      VARCHAR(60) NOT NULL,
    direccion      VARCHAR(60) NOT NULL,
    tipo_documento VARCHAR(12) NOT NULL
    );

CREATE TABLE IF NOT EXISTS venta (
                                     id_venta     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     precio_base  DOUBLE PRECISION NOT NULL,
                                     igv          DOUBLE PRECISION NOT NULL,
                                     precio_total DOUBLE PRECISION NOT NULL,
                                     serie        VARCHAR(10) NOT NULL,
    num_doc      VARCHAR(40) NOT NULL,
    tipo_doc     VARCHAR(20) NOT NULL,
    fecha_gener  DATE NOT NULL,
    dniruc       VARCHAR(12) NOT NULL REFERENCES cliente (dniruc),
    id_usuario   INTEGER NOT NULL REFERENCES usuario (id_usuario)
    );

CREATE TABLE IF NOT EXISTS marca (
                                     id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     nombre   VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS categoria (
                                         id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         nombre       VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS producto (
                                        id_producto   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        nombre        VARCHAR(40) NOT NULL,
    pu            DOUBLE PRECISION NOT NULL,
    puold         DOUBLE PRECISION NOT NULL,
    utilidad      DOUBLE PRECISION NOT NULL,
    stock         DOUBLE PRECISION NOT NULL,
    stockold      DOUBLE PRECISION NOT NULL,
    id_categoria  INTEGER NOT NULL REFERENCES categoria (id_categoria),
    id_marca      INTEGER NOT NULL REFERENCES marca (id_marca),
    id_unidad     INTEGER NOT NULL REFERENCES unid_medida (id_unidad),
    tipo_producto VARCHAR(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS venta_detalle (
                                             id_venta_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             pu               DOUBLE PRECISION NOT NULL,
                                             cantidad         DOUBLE PRECISION NOT NULL,
                                             descuento        DOUBLE PRECISION NOT NULL,
                                             subtotal         DOUBLE PRECISION NOT NULL,
                                             id_venta         INTEGER NOT NULL REFERENCES venta (id_venta),
    id_producto      INTEGER NOT NULL REFERENCES producto (id_producto)
    );

CREATE TABLE IF NOT EXISTS compra_detalle (
                                              id_compra_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                              pu                DOUBLE PRECISION NOT NULL,
                                              cantidad          DOUBLE PRECISION NOT NULL,
                                              subtotal          DOUBLE PRECISION NOT NULL,
                                              id_compra         INTEGER NOT NULL REFERENCES compra (id_compra),
    id_producto       INTEGER NOT NULL REFERENCES producto (id_producto)
    );

-- Datos iniciales (MERGE ... KEY los hace idempotentes)
MERGE INTO perfil (id_perfil, nombre, codigo) KEY (id_perfil) VALUES
    (1, 'Root', 'ROOT'),
    (2, 'Administrador', 'ADM'),
    (3, 'Reporte', 'REP');

MERGE INTO usuario (id_usuario, usuario, clave, estado, id_perfil) KEY (id_usuario)
    VALUES (1, 'admin', 'admin123', 'ACTIVO', 1);

MERGE INTO categoria (id_categoria, nombre) KEY (id_categoria) VALUES (1, 'Televisor');

MERGE INTO marca (id_marca, nombre) KEY (id_marca) VALUES (1, 'LG');

MERGE INTO unid_medida (id_unidad, nombre_medida) KEY (id_unidad) VALUES (1, 'Unidad');

-- H2 no avanza la identidad al insertar IDs explícitos: se reinicia tras los datos iniciales
--ALTER TABLE perfil ALTER COLUMN id_perfil RESTART WITH (SELECT COALESCE(MAX(id_perfil), 0) + 1 FROM perfil);
--ALTER TABLE usuario ALTER COLUMN id_usuario RESTART WITH (SELECT COALESCE(MAX(id_usuario), 0) + 1 FROM usuario);
--ALTER TABLE categoria ALTER COLUMN id_categoria RESTART WITH (SELECT COALESCE(MAX(id_categoria), 0) + 1 FROM categoria);
--ALTER TABLE marca ALTER COLUMN id_marca RESTART WITH (SELECT COALESCE(MAX(id_marca), 0) + 1 FROM marca);
--ALTER TABLE unid_medida ALTER COLUMN id_unidad RESTART WITH (SELECT COALESCE(MAX(id_unidad), 0) + 1 FROM unid_medida);
